[package]
name = "tezos_client"
version = "1.10.0"
authors = ["Branislav Kontur <branislav.kontur@viablesystems.io>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
crypto = { path = "../../crypto" }
tezos_api = { path = "../api" }
tezos_context_api = { path = "../context-api" }
tezos_interop = { path = "../interop" }
tezos_messages = { path = "../messages" }

[dev-dependencies]
assert-json-diff = "2"
strum = "0.20"
thiserror = "1.0"
hex = "0.4"
serde_json = "1.0"
serial_test = "0.5"
